// PostgreSQL 数据编辑提交 apply_changes（T09）。
//
// 对齐 mysql/sqlite：删 → 更新 → 插入，单事务内执行，任何一步失败整体回滚。
// `pg_connect` 每次拨一条全新连接（非注册表复用），因此在本会话上 `BEGIN…COMMIT`
// 不会与其它请求串事务；语句经 `&Client` 顺序执行，错误时 `ROLLBACK` 兜底。
// PG 不经过 sqlx QueryBuilder：SQL 自行拼接，值一律 `$n` 参数化绑定，标识符 `pg_quote_identifier`。
// 二进制（bytea）写入以 `Vec<u8>` 直接绑定；Hex 编辑回写前由 app 转成 `CellValue::Bytes`。

fn pg_apply_changes(
    config: &ConnectionConfig,
    changes: &DataChangeSet,
) -> fluxdb_core::Result<AppliedChangeOutcome> {
    validate_data_changes(changes)?;

    let database = changes
        .object
        .database
        .as_deref()
        .ok_or_else(|| Error::new(ErrorKind::Query, "缺少数据库名称"))?;

    pg_runtime().block_on(async {
        let session = pg_connect(config, database).await?;
        let client = session.client.as_ref();
        let table = pg_qualified_table(database, changes.object.schema.as_deref(), &changes.object.name);
        // 先取列元数据（元数据查询与事务解耦）。
        let columns = pg_columns(client, database, changes.object.schema.as_deref(), &changes.object.name)
            .await?;
        // 服务端生成列（generated/identity）不可写：插入时排除、更新时拒绝。
        let generated = pg_generated_columns(client, database, changes.object.schema.as_deref(), &changes.object.name)
            .await?;

        client
            .batch_execute("BEGIN")
            .await
            .map_err(|error| Error::new(ErrorKind::Query, error.to_string()))?;

        let result = async {
            pg_apply_deletes(client, &table, changes, &columns).await?;
            pg_apply_updates(client, &table, changes, &columns, &generated).await?;
            let inserted_identities =
                pg_apply_inserts(client, &table, changes, &columns, &generated).await?;
            Ok::<_, fluxdb_core::Error>(AppliedChangeOutcome {
                inserted_identities,
            })
        }
        .await;

        match result {
            Ok(outcome) => {
                client
                    .batch_execute("COMMIT")
                    .await
                    .map_err(|error| Error::new(ErrorKind::Query, error.to_string()))?;
                Ok(outcome)
            }
            Err(error) => {
                let _ = client.batch_execute("ROLLBACK").await;
                Err(error)
            }
        }
    })
}

/// 查询服务端生成列（`GENERATED ... AS` 或 `GENERATED BY DEFAULT/ALWAYS AS IDENTITY`）。
/// 这类列由数据库生成，写入会失败或语义错误，插入列列表须剔除、更新 SET 须拒绝。
async fn pg_generated_columns(
    client: &tokio_postgres::Client,
    database: &str,
    schema: Option<&str>,
    table: &str,
) -> fluxdb_core::Result<std::collections::BTreeSet<String>> {
    let _ = database;
    let schema_name = schema.unwrap_or("public");
    let rows = client
        .query(
            r#"
            SELECT a.attname
            FROM pg_attribute a
            JOIN pg_class c ON c.oid = a.attrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = $1 AND n.nspname = $2
              AND a.attnum > 0 AND NOT a.attisdropped
              AND (a.attgenerated <> '' OR a.attidentity <> '')
            "#,
            &[&table, &schema_name],
        )
        .await
        .map_err(pg_error)?;
    Ok(rows.into_iter().map(|row| row.get(0)).collect())
}

/// 解析一行插入值：按表列序返回需写入的 `(列, 值)`。
///
/// 未提供三态意图时退回 `non_null_insert_values` 旧语义（NULL 视为省略 → DEFAULT）；
/// 提供意图时按列对齐，`Default` 省略、`Null` 显式写 NULL、`Value` 写具体值，
/// 从而能对带默认值/可空的列显式写 NULL。服务端生成列一律剔除。
fn pg_insert_values<'a>(
    row: &'a Row,
    columns: &'a [Column],
    generated: &std::collections::BTreeSet<String>,
    intents: Option<&'a [WriteValue]>,
) -> fluxdb_core::Result<Vec<(&'a Column, &'a CellValue)>> {
    let Some(intents) = intents else {
        return Ok(non_null_insert_values(row, columns)?
            .into_iter()
            .filter(|(column, _)| !generated.contains(&column.name))
            .collect());
    };
    if intents.len() != columns.len() {
        return Err(Error::new(ErrorKind::Internal, "插入写入意图与列数不匹配"));
    }
    let mut out = Vec::new();
    for (column, intent) in columns.iter().zip(intents) {
        if generated.contains(&column.name) {
            continue; // 服务端生成列不可写
        }
        match intent {
            WriteValue::Default => {} // 省略 → 数据库默认值填充
            WriteValue::Null => out.push((column, &CellValue::Null)),
            WriteValue::Value(value) => out.push((column, value)),
        }
    }
    Ok(out)
}

/// 插入行并回传真实身份（§8.4/R11）。
///
/// 自增/序列/默认值生成的主键无法从编辑输入得知，故 INSERT 追加 `RETURNING` 主键列，
/// 用服务端返回值构造行身份——补偿 SQL 才能定位到真正插入的那一行。
async fn pg_apply_inserts(
    client: &tokio_postgres::Client,
    table: &str,
    changes: &DataChangeSet,
    columns: &[Column],
    generated: &std::collections::BTreeSet<String>,
) -> fluxdb_core::Result<Vec<RowIdentity>> {
    let primary_keys = columns
        .iter()
        .filter(|column| column.primary_key)
        .map(|column| (column.name.clone(), column.clone()))
        .collect::<Vec<_>>();
    let mut identities = Vec::with_capacity(changes.inserts.len());
    for (index, row) in changes.inserts.iter().enumerate() {
        // 清除服务端生成列（其值由数据库产生）；意图三态时逐列对齐，
        // 否则退回旧语义（NULL 视为省略 → DEFAULT）。
        let insert_values = pg_insert_values(row, columns, generated, changes.insert_intents_for(index))?;
        let (sql, params) = pg_insert_sql(table, &insert_values)?;
        if primary_keys.is_empty() {
            client
                .execute(&sql, &pg_params_refs(&params))
                .await
                .map_err(|error| Error::new(ErrorKind::Query, error.to_string()))?;
            continue;
        }
        let returning = primary_keys
            .iter()
            .map(|(name, _)| pg_quote_identifier(name))
            .collect::<Vec<_>>()
            .join(", ");
        let sql = format!("{sql} RETURNING {returning}");
        let returned = client
            .query(&sql, &pg_params_refs(&params))
            .await
            .map_err(|error| Error::new(ErrorKind::Query, error.to_string()))?;
        let Some(returned) = returned.into_iter().next() else {
            continue;
        };
        let mut values = std::collections::BTreeMap::new();
        for (position, (name, column)) in primary_keys.iter().enumerate() {
            values.insert(name.clone(), pg_projected_cell_value(&returned, position, column));
        }
        identities.push(RowIdentity { values });
    }
    Ok(identities)
}

async fn pg_apply_updates(
    client: &tokio_postgres::Client,
    table: &str,
    changes: &DataChangeSet,
    columns: &[Column],
    generated: &std::collections::BTreeSet<String>,
) -> fluxdb_core::Result<()> {
    for update in &changes.updates {
        if update.cells.is_empty() {
            continue;
        }
        for cell in &update.cells {
            ensure_column_exists(&cell.column, columns)?;
            // 服务端生成列不可写：拒绝，避免覆盖数据库生成值。
            if generated.contains(&cell.column) {
                return Err(Error::new(
                    ErrorKind::Query,
                    format!("生成列不可直接修改: {}", cell.column),
                ));
            }
        }
        validate_identity(&update.identity, columns)?;

        let (sql, params) = pg_update_sql(table, &update.cells, &update.identity, columns)?;
        // 行数检查：期望恰好 1 行。0 行=目标消失/并发冲突，>1=身份不唯一；均回滚。
        let affected = client
            .execute(&sql, &pg_params_refs(&params))
            .await
            .map_err(|error| Error::new(ErrorKind::Query, error.to_string()))?;
        if affected != 1 {
            return Err(update_conflict_error(affected));
        }
    }
    Ok(())
}

async fn pg_apply_deletes(
    client: &tokio_postgres::Client,
    table: &str,
    changes: &DataChangeSet,
    columns: &[Column],
) -> fluxdb_core::Result<()> {
    for identity in &changes.deletes {
        validate_identity(identity, columns)?;
        let (where_sql, params) = pg_identity_params(identity, columns)?;
        let sql = format!("DELETE FROM {table}{where_sql}");
        // 行数检查：期望恰好 1 行，0/>1 均视为并发冲突或身份不唯一，整体回滚。
        let affected = client
            .execute(&sql, &pg_params_refs(&params))
            .await
            .map_err(|error| Error::new(ErrorKind::Query, error.to_string()))?;
        if affected != 1 {
            return Err(update_conflict_error(affected));
        }
    }
    Ok(())
}

/// 更新/删除影响行数与期望不符时的并发冲突错误（设计 7.3：0 行消失、>1 身份不唯一）。
fn update_conflict_error(affected: u64) -> fluxdb_core::Error {
    let message = if affected == 0 {
        "目标行已不存在或已被并发修改，已回滚本次提交".to_string()
    } else {
        "行身份不唯一，命中了多行，已回滚本次提交".to_string()
    };
    Error::new(ErrorKind::Query, message)
}

fn pg_insert_sql(
    table: &str,
    values: &[(&Column, &CellValue)],
) -> fluxdb_core::Result<(String, Vec<Box<dyn ToSql + Sync>>)> {
    if values.is_empty() {
        // 全部字段为 NULL 时退化为默认值插入。
        return Ok((format!("INSERT INTO {table} DEFAULT VALUES"), Vec::new()));
    }

    let mut params: Vec<Box<dyn ToSql + Sync>> = Vec::new();
    let column_list = values
        .iter()
        .map(|(column, _)| pg_quote_identifier(&column.name))
        .collect::<Vec<_>>()
        .join(", ");
    let placeholders = values
        .iter()
        .map(|(column, value)| pg_bind_sql(&mut params, column, value))
        .collect::<Vec<_>>()
        .join(", ");
    Ok((
        format!("INSERT INTO {table} ({column_list}) VALUES ({placeholders})"),
        params,
    ))
}

fn pg_update_sql(
    table: &str,
    cells: &[fluxdb_core::CellUpdate],
    identity: &fluxdb_core::RowIdentity,
    columns: &[Column],
) -> fluxdb_core::Result<(String, Vec<Box<dyn ToSql + Sync>>)> {
    let mut params: Vec<Box<dyn ToSql + Sync>> = Vec::new();
    let sets = cells
        .iter()
        .map(|cell| {
            let col = columns
                .iter()
                .find(|column| column.name == cell.column)
                .ok_or_else(|| Error::new(ErrorKind::Query, "更新引用了不存在的列"))?;
            Ok(format!(
                "{} = {}",
                pg_quote_identifier(&cell.column),
                pg_bind_sql(&mut params, col, &cell.value)
            ))
        })
        .collect::<Result<Vec<_>, _>>()?
        .join(", ");
    // 身份条件继续沿用同一参数序号（紧跟 SET 之后）。
    let where_sql = pg_identity_where(&mut params, identity, columns)?;
    Ok((
        format!("UPDATE {table} SET {sets}{where_sql}"),
        params,
    ))
}

/// 把行身份写成参数化 WHERE 并追加到既有参数表（保证 `$n` 序号连续）。空身份则报错。
fn pg_identity_where(
    params: &mut Vec<Box<dyn ToSql + Sync>>,
    identity: &fluxdb_core::RowIdentity,
    columns: &[Column],
) -> fluxdb_core::Result<String> {
    let mut clauses = Vec::new();
    for (column, value) in &identity.values {
        let col = columns
            .iter()
            .find(|col| &col.name == column)
            .ok_or_else(|| Error::new(ErrorKind::Query, "行身份引用了不存在的列"))?;
        let quoted = pg_quote_identifier(column);
        if matches!(value, CellValue::Null) {
            clauses.push(format!("{quoted} IS NULL"));
        } else {
            clauses.push(format!("{quoted} = {}", pg_bind_sql(params, col, value)));
        }
    }
    if clauses.is_empty() {
        return Err(Error::new(ErrorKind::Query, "缺少行身份条件，已取消提交"));
    }
    Ok(format!(" WHERE {}", clauses.join(" AND ")))
}
