#[test]
fn postgres_create_table_preview_covers_columns_keys_indexes_comments() {
    let mut create = CreateTableState::new(
        ConnectionId(9),
        Some("appdb".to_string()),
        DatabaseKind::Postgres,
    );
    create.schema = "sales".to_string();
    create.table_name = "orders".to_string();
    create.comment = "订单表".to_string();

    // identity 主键列（复用 auto_increment 能力位，PG 渲染为 GENERATED BY DEFAULT AS IDENTITY）。
    let provider = create_table_provider(DatabaseKind::Postgres);
    let mut id_column = CreateTableColumn::new(1, provider);
    id_column.name = "id".to_string();
    id_column.data_type = "integer".to_string();
    id_column.nullable = false;
    id_column.primary_key = true;
    id_column.auto_increment = true;
    let mut amount_column = CreateTableColumn::new(2, provider);
    amount_column.name = "amount".to_string();
    amount_column.data_type = "numeric".to_string();
    amount_column.length = "10".to_string();
    amount_column.scale = "2".to_string();
    amount_column.nullable = false;
    amount_column.default_value = "0".to_string();
    amount_column.comment = "金额".to_string();
    let mut customer_column = CreateTableColumn::new(3, provider);
    customer_column.name = "customer_id".to_string();
    customer_column.data_type = "integer".to_string();
    customer_column.nullable = false;
    create.columns = vec![id_column, amount_column, customer_column];
    create.indexes = vec![CreateTableIndex {
        id: 1,
        name: "idx_orders_amount".to_string(),
        columns: vec![CreateTableIndexColumn {
            name: "amount".to_string(),
            sub_part: String::new(),
            sort_order: "DESC".to_string(),
        }],
        index_type: "NORMAL".to_string(),
        index_method: "BTREE".to_string(),
        comment: String::new(),
    }];
    create.indexes.push(CreateTableIndex {
        id: 2,
        name: "uq_orders_customer".to_string(),
        columns: vec![CreateTableIndexColumn {
            name: "customer_id".to_string(),
            sub_part: String::new(),
            sort_order: String::new(),
        }],
        index_type: "UNIQUE".to_string(),
        index_method: String::new(),
        comment: String::new(),
    });
    create.foreign_keys = vec![CreateTableForeignKey {
        id: 1,
        name: "fk_orders_customer".to_string(),
        columns: vec!["customer_id".to_string()],
        referenced_database: "public".to_string(),
        referenced_table: "customers".to_string(),
        referenced_columns: vec!["id".to_string()],
        referenced_column_options: LoadState::Loaded(vec!["id".to_string()]),
        on_delete: "CASCADE".to_string(),
        on_update: String::new(),
    }];
    create.checks = vec![CreateTableCheck {
        id: 1,
        name: "ck_orders_amount".to_string(),
        expression: "amount >= 0".to_string(),
        not_enforced: false,
    }];

    let sql = create.sql_preview().expect("PG 建表预览应成功");

    // schema 限定 + 双引号标识符（不是 MySQL 反引号）。
    assert!(
        sql.starts_with("CREATE TABLE \"sales\".\"orders\" ("),
        "应带 schema 限定：{sql}"
    );
    // identity 而非 AUTO_INCREMENT。
    assert!(
        sql.contains("\"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL"),
        "identity 列应渲染为 GENERATED BY DEFAULT AS IDENTITY：{sql}"
    );
    assert!(!sql.contains("AUTO_INCREMENT"), "不得出现 MySQL 属性：{sql}");
    // numeric 精度保留。
    assert!(sql.contains("\"amount\" numeric(10,2) NOT NULL DEFAULT 0"), "{sql}");
    // 主键 / check 约束行。
    assert!(sql.contains("PRIMARY KEY (\"id\")"), "{sql}");
    assert!(
        sql.contains("CONSTRAINT \"ck_orders_amount\" CHECK (amount >= 0)"),
        "{sql}"
    );
    // FK：referenced_database 承载 schema，始终带限定（不依赖 search_path）。
    assert!(
        sql.contains(
            "CONSTRAINT \"fk_orders_customer\" FOREIGN KEY (\"customer_id\") REFERENCES \"public\".\"customers\" (\"id\") ON DELETE CASCADE"
        ),
        "{sql}"
    );
    // 注释是独立 COMMENT ON 语句。
    assert!(sql.contains("COMMENT ON TABLE \"sales\".\"orders\" IS '订单表';"), "{sql}");
    assert!(
        sql.contains("COMMENT ON COLUMN \"sales\".\"orders\".\"amount\" IS '金额';"),
        "{sql}"
    );
    // 索引：PG 的 CREATE [UNIQUE] INDEX（BTREE 是默认，不写 USING）。
    assert!(
        sql.contains(
            "CREATE INDEX \"idx_orders_amount\" ON \"sales\".\"orders\" (\"amount\" DESC);"
        ),
        "{sql}"
    );
    assert!(
        sql.contains("CREATE UNIQUE INDEX \"uq_orders_customer\" ON \"sales\".\"orders\" (\"customer_id\");"),
        "{sql}"
    );
}

#[test]
fn postgres_create_table_rejects_mysql_only_and_inline_trigger() {
    // identity 挂在非整数列：应拒绝而不是生成 PG 无法执行的 DDL。
    let mut create = CreateTableState::new(ConnectionId(9), None, DatabaseKind::Postgres);
    create.table_name = "t".to_string();
    let provider = create_table_provider(DatabaseKind::Postgres);
    let mut id_column = CreateTableColumn::new(1, provider);
    id_column.name = "id".to_string();
    id_column.data_type = "text".to_string();
    id_column.nullable = false;
    id_column.auto_increment = true;
    create.columns = vec![id_column];
    assert_eq!(
        create.validation_error(),
        Some("PostgreSQL identity 只能用于整数类型列")
    );

    // MySQL 行内 BEGIN…END 触发器体不是 PG 触发器：必须明确拒绝。
    create.columns[0].auto_increment = false;
    create.columns[0].primary_key = true;
    create.triggers = vec![CreateTableTrigger {
        id: 1,
        name: "tg".to_string(),
        timing: "BEFORE".to_string(),
        event: "INSERT".to_string(),
        body: "BEGIN RETURN NEW; END".to_string(),
    }];
    assert_eq!(
        create.validation_error(),
        Some("PostgreSQL 触发器需要引用已存在的函数，不支持行内 BEGIN…END 触发器体")
    );

    // 引用已存在函数则可生成 CREATE TRIGGER ... EXECUTE FUNCTION。
    create.triggers[0].body = "audit_row".to_string();
    let sql = create.sql_preview().expect("引用函数的触发器应可生成");
    assert!(
        sql.contains(
            "CREATE TRIGGER \"tg\" BEFORE INSERT ON \"t\" FOR EACH ROW EXECUTE FUNCTION \"audit_row\"();"
        ),
        "{sql}"
    );
}

#[test]
fn postgres_create_table_type_capabilities_hide_mysql_options() {
    let provider = create_table_provider(DatabaseKind::Postgres);
    assert_eq!(provider.default_column_type(), "text");
    assert_eq!(provider.default_id_type(), "integer");
    assert!(provider.type_options().contains(&"jsonb"));

    let integer = provider.type_capabilities("integer");
    assert!(integer.auto_increment, "整数列应可设 identity");
    assert!(!integer.unsigned && !integer.zerofill && !integer.auto_update_time);

    let varchar = provider.type_capabilities("varchar");
    assert!(varchar.length);
    assert!(!varchar.key_length && !varchar.binary_attribute && !varchar.text_options);

    let numeric = provider.type_capabilities("numeric");
    assert!(numeric.scale && !numeric.length);

    // 未列在类型清单里的 MySQL 类型不应带 MySQL 专属能力。
    let text_type = provider.type_capabilities("mediumtext");
    assert!(
        !text_type.length && !text_type.text_options && !text_type.auto_increment,
        "PG 不展示 MySQL 文本类型能力"
    );
}

/// 取 PG provider 的差异语句（测试注意力放在语句本身）。
fn postgres_design_statements(create: &CreateTableState) -> Result<Vec<String>, String> {
    create_table_provider(DatabaseKind::Postgres).design_statements(create)
}

/// 用设计模式构造一个 PG 表状态：原表有 id/note 两列、id 为主键。
fn postgres_design_state() -> CreateTableState {
    let object = ObjectPath {
        connection_id: ConnectionId(9),
        database: Some("appdb".to_string()),
        schema: Some("sales".to_string()),
        name: "orders".to_string(),
        kind: ObjectKind::Table,
    };
    let columns = vec![
        CompletionColumn {
            database: Some("appdb".to_string()),
            schema: Some("sales".to_string()),
            table: "orders".to_string(),
            name: "id".to_string(),
            type_name: Some("integer".to_string()),
            nullable: false,
            primary_key: true,
            comment: None,
        },
        CompletionColumn {
            database: Some("appdb".to_string()),
            schema: Some("sales".to_string()),
            table: "orders".to_string(),
            name: "note".to_string(),
            type_name: Some("text".to_string()),
            nullable: true,
            primary_key: false,
            comment: None,
        },
    ];
    let ddl = "CREATE TABLE \"sales\".\"orders\" (\n  \"id\" integer NOT NULL,\n  \"note\" text,\n  CONSTRAINT \"orders_pkey\" PRIMARY KEY (\"id\")\n);".to_string();
    CreateTableState::design(
        object,
        DatabaseKind::Postgres,
        columns,
        Vec::new(),
        Vec::new(),
        Vec::new(),
        Some(ddl),
    )
}

/// §9.2：无修改必须无 SQL（不生成任何 ALTER）。
#[test]
fn postgres_design_without_changes_generates_no_sql() {
    let create = postgres_design_state();
    let statements = postgres_design_statements(&create).expect("无变更应成功");
    assert!(
        statements.is_empty(),
        "无修改不应生成 SQL：{statements:#?}"
    );
    // 预览层对「无变更」给出明确提示，而不是空 SQL。
    assert_eq!(
        create.sql_preview().unwrap_err(),
        "没有需要保存的变更"
    );
}

/// §9.2：增删改名/默认值/类型/NULL/identity/注释转成有序 PG 动作。
#[test]
fn postgres_design_column_changes_become_ordered_actions() {
    let mut create = postgres_design_state();
    let mut renamed = create.columns[1].clone();
    renamed.name = "memo".to_string();
    renamed.nullable = false;
    renamed.default_value = "'n/a'".to_string();
    renamed.comment = "备注".to_string();
    let mut price = CreateTableColumn::new(3, create_table_provider(DatabaseKind::Postgres));
    price.name = "amount".to_string();
    price.data_type = "numeric".to_string();
    price.length = "10".to_string();
    price.scale = "2".to_string();
    price.nullable = false;
    price.auto_increment = true;
    // identity 只能挂整数列：用整数类型验证 identity 动作。
    price.data_type = "bigint".to_string();
    price.length.clear();
    price.scale.clear();
    create.columns = vec![create.columns[0].clone(), renamed, price];

    let statements = postgres_design_statements(&create).expect("列变更应成功");
    assert_eq!(
        statements,
        vec![
            "ALTER TABLE \"sales\".\"orders\" RENAME COLUMN \"note\" TO \"memo\";".to_string(),
            "ALTER TABLE \"sales\".\"orders\" ALTER COLUMN \"memo\" SET DEFAULT 'n/a';".to_string(),
            "ALTER TABLE \"sales\".\"orders\" ALTER COLUMN \"memo\" SET NOT NULL;".to_string(),
            "COMMENT ON COLUMN \"sales\".\"orders\".\"memo\" IS '备注';".to_string(),
            "ALTER TABLE \"sales\".\"orders\" ADD COLUMN \"amount\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;".to_string(),
        ],
        "列变更应生成有序 ALTER（改名先于其它动作）：{statements:#?}"
    );

    // 删除列 + 改类型 + 去默认值 + 放开 NOT NULL。
    let mut dropped = postgres_design_state();
    let mut typed = dropped.columns[1].clone();
    typed.data_type = "varchar".to_string();
    typed.length = "64".to_string();
    dropped.columns[1] = typed;
    dropped.columns[0].primary_key = false;
    dropped.columns[0].nullable = true;
    dropped.columns[0].default_value = "0".to_string();
    let statements = postgres_design_statements(&dropped).expect("类型/默认值变更应成功");
    assert!(
        statements
            .iter()
            .any(|sql| sql == "ALTER TABLE \"sales\".\"orders\" ALTER COLUMN \"note\" TYPE varchar(64);"),
        "类型变更应生成 ALTER COLUMN TYPE：{statements:#?}"
    );
    assert!(
        statements.iter().any(|sql| sql
            == "ALTER TABLE \"sales\".\"orders\" ALTER COLUMN \"id\" SET DEFAULT 0;"),
        "{statements:#?}"
    );
    assert!(
        statements.iter().any(|sql| sql
            == "ALTER TABLE \"sales\".\"orders\" ALTER COLUMN \"id\" DROP NOT NULL;"),
        "{statements:#?}"
    );
    // 主键移除：从展示 DDL 解析出的约束名，而不是猜默认名。
    assert!(
        statements.iter().any(|sql| sql
            == "ALTER TABLE \"sales\".\"orders\" DROP CONSTRAINT \"orders_pkey\";"),
        "主键变化应丢弃原约束（名字取自 DDL）：{statements:#?}"
    );
    // 不自动编造 USING 表达式。
    assert!(
        !statements.iter().any(|sql| sql.contains("USING")),
        "不应自动编造 USING：{statements:#?}"
    );
}

/// §9.2：索引/FK/check/触发器/表注释的增删走 PG 语法；未知属性不被触碰。
#[test]
fn postgres_design_object_changes_use_postgres_syntax() {
    let mut create = postgres_design_state();
    create.comment = "订单表".to_string();
    create.indexes = vec![CreateTableIndex {
        id: 1,
        name: "idx_orders_note".to_string(),
        columns: vec![CreateTableIndexColumn {
            name: "note".to_string(),
            sub_part: String::new(),
            sort_order: String::new(),
        }],
        index_type: "NORMAL".to_string(),
        index_method: String::new(),
        comment: String::new(),
    }];
    create.checks = vec![CreateTableCheck {
        id: 1,
        name: "ck_orders_note".to_string(),
        expression: "note <> ''".to_string(),
        not_enforced: false,
    }];

    let statements = postgres_design_statements(&create).expect("对象变更应成功");
    assert!(
        statements.contains(
            &"CREATE INDEX \"idx_orders_note\" ON \"sales\".\"orders\" (\"note\");".to_string()
        ),
        "索引应生成独立 CREATE INDEX：{statements:#?}"
    );
    assert!(
        statements.contains(
            &"ALTER TABLE \"sales\".\"orders\" ADD CONSTRAINT \"ck_orders_note\" CHECK (note <> '');"
                .to_string()
        ),
        "{statements:#?}"
    );
    assert!(
        statements.contains(&"COMMENT ON TABLE \"sales\".\"orders\" IS '订单表';".to_string()),
        "{statements:#?}"
    );
    // 只发差异动作：不重建表、不删除未改动的结构（RLS/分区等未知定义因此在原地保留）。
    assert!(
        !statements.iter().any(|sql| sql.contains("CREATE TABLE")),
        "设计保存不得重建整表：{statements:#?}"
    );
    assert!(
        !statements
            .iter()
            .any(|sql| sql.contains("DROP COLUMN \"id\"") || sql.contains("DROP COLUMN \"note\"")),
        "未删除的列不应出现在 DROP：{statements:#?}"
    );

    // 触发器：PG 用引用函数的 CREATE TRIGGER，删除要带 ON 表。
    let mut with_trigger = postgres_design_state();
    with_trigger.triggers = vec![CreateTableTrigger {
        id: 1,
        name: "trg_orders".to_string(),
        timing: "BEFORE".to_string(),
        event: "INSERT".to_string(),
        body: "audit_row".to_string(),
    }];
    let statements = postgres_design_statements(&with_trigger).expect("触发器变更应成功");
    assert!(
        statements.contains(
            &"CREATE TRIGGER \"trg_orders\" BEFORE INSERT ON \"sales\".\"orders\" FOR EACH ROW EXECUTE FUNCTION \"audit_row\"();"
                .to_string()
        ),
        "{statements:#?}"
    );
    assert!(
        statements.iter().all(|sql| !sql.starts_with("ALTER TABLE")),
        "触发器不应被塞进 ALTER TABLE：{statements:#?}"
    );
}

/// §9.2：索引删除走 DROP INDEX，且带 schema 限定（同名索引可在别的 schema 存在）。
#[test]
fn postgres_design_drops_index_with_schema_qualification() {
    let mut create = postgres_design_state();
    let original_index = CreateTableIndex {
        id: 1,
        name: "idx_orders_note".to_string(),
        columns: vec![CreateTableIndexColumn {
            name: "note".to_string(),
            sub_part: String::new(),
            sort_order: String::new(),
        }],
        index_type: "NORMAL".to_string(),
        index_method: String::new(),
        comment: String::new(),
    };
    if let CreateTableMode::Design { original, .. } = &mut create.mode {
        original.indexes = vec![original_index];
    }
    let statements = postgres_design_statements(&create).expect("索引删除应成功");
    assert_eq!(
        statements,
        vec!["DROP INDEX \"sales\".\"idx_orders_note\";".to_string()],
        "{statements:#?}"
    );
}

/// §9.2：约束/触发器的删除走 PG 的 DROP CONSTRAINT / DROP TRIGGER ON。
#[test]
fn postgres_design_drops_constraints_and_triggers() {
    let mut create = postgres_design_state();
    if let CreateTableMode::Design { original, .. } = &mut create.mode {
        original.foreign_keys = vec![CreateTableForeignKey {
            id: 1,
            name: "fk_orders_customer".to_string(),
            columns: vec!["note".to_string()],
            referenced_database: "sales".to_string(),
            referenced_table: "customers".to_string(),
            referenced_columns: vec!["id".to_string()],
            referenced_column_options: LoadState::Loaded(vec!["id".to_string()]),
            on_delete: String::new(),
            on_update: String::new(),
        }];
        original.checks = vec![CreateTableCheck {
            id: 1,
            name: "ck_orders_note".to_string(),
            expression: "note <> ''".to_string(),
            not_enforced: false,
        }];
        original.triggers = vec![CreateTableTrigger {
            id: 1,
            name: "trg_orders".to_string(),
            timing: "BEFORE".to_string(),
            event: "INSERT".to_string(),
            body: "audit_row".to_string(),
        }];
    }

    let statements = postgres_design_statements(&create).expect("删除约束应成功");
    assert_eq!(
        statements,
        vec![
            "ALTER TABLE \"sales\".\"orders\" DROP CONSTRAINT \"fk_orders_customer\";".to_string(),
            "ALTER TABLE \"sales\".\"orders\" DROP CONSTRAINT \"ck_orders_note\";".to_string(),
            "DROP TRIGGER \"trg_orders\" ON \"sales\".\"orders\";".to_string(),
        ],
        "约束与触发器删除应按 PG 语法生成：{statements:#?}"
    );
}

/// §9.3：PG 表操作按 schema 限定、按 kind 选 DDL、默认 RESTRICT/CONTINUE IDENTITY。
#[test]
fn postgres_table_actions_are_schema_qualified_and_kind_aware() {
    // 重命名：旧名带 schema，新名是单段。
    assert_eq!(
        rename_table_sql_preview(DatabaseKind::Postgres, Some("sales"), "orders", "orders_2026")
            .unwrap(),
        "ALTER TABLE \"sales\".\"orders\" RENAME TO \"orders_2026\";"
    );
    // 新名带点号会被误当成限定名，必须拒绝。
    assert!(
        rename_table_sql_preview(DatabaseKind::Postgres, Some("sales"), "orders", "a.b").is_err()
    );

    // 复制：LIKE INCLUDING ALL + 序列重绑 + 可选数据。
    let copy = copy_table_sql_preview(DatabaseKind::Postgres, Some("sales"), "orders", "copy", true)
        .unwrap();
    assert!(
        copy.starts_with("CREATE TABLE \"sales\".\"copy\" (LIKE \"sales\".\"orders\" INCLUDING ALL);"),
        "{copy}"
    );
    assert!(copy.contains("CREATE SEQUENCE"), "复制必须重建独立序列：{copy}");
    // 数据复制走 DO 块：跳过生成列、identity 用 OVERRIDING SYSTEM VALUE、复制后校准序列位置。
    assert!(copy.contains("OVERRIDING SYSTEM VALUE"), "{copy}");
    assert!(copy.contains("setval("), "复制后应校准序列位置：{copy}");
    assert!(!copy.contains("SELECT * FROM"), "生成列不能参与写入：{copy}");

    // 删除：表/视图对应不同 DDL，默认 RESTRICT（不带 CASCADE）。
    assert_eq!(
        drop_table_sql_preview(DatabaseKind::Postgres, ObjectKind::Table, Some("sales"), "orders", ForeignKeyCheckMode::Default)
            .unwrap(),
        "DROP TABLE \"sales\".\"orders\";"
    );
    assert_eq!(
        drop_table_sql_preview(DatabaseKind::Postgres, ObjectKind::View, Some("sales"), "orders_v", ForeignKeyCheckMode::Default)
            .unwrap(),
        "DROP VIEW \"sales\".\"orders_v\";"
    );

    // 清空：默认 CONTINUE IDENTITY RESTRICT，显式选择才 RESTART IDENTITY。
    assert_eq!(
        truncate_table_sql_preview(
            DatabaseKind::Postgres,
            Some("sales"),
            "orders",
            false,
            ForeignKeyCheckMode::Default
        )
        .unwrap(),
        "TRUNCATE TABLE \"sales\".\"orders\" CONTINUE IDENTITY RESTRICT;"
    );
    assert_eq!(
        truncate_table_sql_preview(
            DatabaseKind::Postgres,
            Some("sales"),
            "orders",
            true,
            ForeignKeyCheckMode::Default
        )
        .unwrap(),
        "TRUNCATE TABLE \"sales\".\"orders\" RESTART IDENTITY RESTRICT;"
    );

    // PG 不提供「禁用外键检查」，且不得退化成 session_replication_role。
    let error = drop_table_sql_preview(
        DatabaseKind::Postgres,
        ObjectKind::Table,
        Some("sales"),
        "orders",
        ForeignKeyCheckMode::Disable,
    )
    .unwrap_err();
    assert!(error.contains("不支持禁用外键检查"), "{error}");
    assert!(!error.contains("session_replication_role"), "{error}");
}

/// MySQL 表操作 SQL 未变（回归）。
#[test]
fn mysql_table_actions_unchanged_by_postgres_provider() {
    assert_eq!(
        rename_table_sql_preview(DatabaseKind::MySql, None, "orders", "orders_2026").unwrap(),
        "ALTER TABLE `orders` RENAME TO `orders_2026`;"
    );
    assert_eq!(
        truncate_table_sql_preview(
            DatabaseKind::MySql,
            None,
            "orders",
            true,
            ForeignKeyCheckMode::Default
        )
        .unwrap(),
        "TRUNCATE TABLE `orders`;"
    );
    assert_eq!(
        drop_table_sql_preview(
            DatabaseKind::MySql,
            ObjectKind::Table,
            None,
            "orders",
            ForeignKeyCheckMode::Disable
        )
        .unwrap(),
        "SET FOREIGN_KEY_CHECKS = 0;\nDROP TABLE `orders`;"
    );
}
