/// T16 验收：生成的 PG 建表 DDL 在真实数据库隔离 schema 内重建后元数据对等。
///
/// 用 `FLUXDB_PG_SMOKE=host:port:user:password:db` 开启真实 PG 冒烟；未配置时跳过。
/// 断言覆盖：列/联合主键/唯一索引/FK/check/表列注释全部落库，且回读元数据与设计一致。
#[test]
fn postgres_create_table_ddl_rebuilds_equivalent_metadata() {
    let Some(params) = postgres_create_table_smoke_params() else {
        tracing::warn!(target: "fluxdb_app", "未设置 FLUXDB_PG_SMOKE，跳过真实 PG T16 冒烟");
        return;
    };
    let config = postgres_create_table_smoke_config(&params);
    let connector = PostgresConnector::with_config(config.clone());
    let database = params.4.clone();

    let mut setup = QueryRequest {
        connection_id: config.id,
        database: Some(database.clone()),
        session_id: None,
        schema: None,
        text: "\
            DROP SCHEMA IF EXISTS t16_smoke CASCADE; \
            CREATE SCHEMA t16_smoke; \
            CREATE TABLE t16_smoke.customers(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL); \
        "
        .to_string(),
        mode: fluxdb_core::QueryMode::All,
        options: QueryExecutionOptions::default(),
    };
    connector.execute(&setup).expect("建隔离 schema 应成功");

    // 领域结构 → DDL（provider 生成，UI 不拼 SQL）。
    let provider = create_table_provider(DatabaseKind::Postgres);
    let mut create = CreateTableState::new(config.id, Some(database.clone()), DatabaseKind::Postgres);
    create.schema = "t16_smoke".to_string();
    create.table_name = "orders".to_string();
    create.comment = "订单表".to_string();

    let mut id_column = CreateTableColumn::new(1, provider);
    id_column.name = "id".to_string();
    id_column.data_type = "integer".to_string();
    id_column.nullable = false;
    id_column.primary_key = true;
    id_column.auto_increment = true;
    id_column.comment = "主键".to_string();
    let mut customer_column = CreateTableColumn::new(2, provider);
    customer_column.name = "customer_id".to_string();
    customer_column.data_type = "integer".to_string();
    customer_column.nullable = false;
    let mut amount_column = CreateTableColumn::new(3, provider);
    amount_column.name = "amount".to_string();
    amount_column.data_type = "numeric".to_string();
    amount_column.length = "10".to_string();
    amount_column.scale = "2".to_string();
    amount_column.nullable = false;
    amount_column.default_value = "0".to_string();
    let mut note_column = CreateTableColumn::new(4, provider);
    note_column.name = "note".to_string();
    note_column.data_type = "text".to_string();
    note_column.nullable = true;
    create.columns = vec![id_column, customer_column, amount_column, note_column];

    create.indexes = vec![CreateTableIndex {
        id: 1,
        name: "uq_t16_orders_customer_amount".to_string(),
        columns: vec![
            CreateTableIndexColumn {
                name: "customer_id".to_string(),
                sub_part: String::new(),
                sort_order: String::new(),
            },
            CreateTableIndexColumn {
                name: "amount".to_string(),
                sub_part: String::new(),
                sort_order: String::new(),
            },
        ],
        index_type: "UNIQUE".to_string(),
        index_method: String::new(),
        comment: String::new(),
    }];
    create.foreign_keys = vec![CreateTableForeignKey {
        id: 1,
        name: "fk_t16_orders_customer".to_string(),
        columns: vec!["customer_id".to_string()],
        referenced_database: "t16_smoke".to_string(),
        referenced_table: "customers".to_string(),
        referenced_columns: vec!["id".to_string()],
        referenced_column_options: LoadState::Loaded(vec!["id".to_string()]),
        on_delete: "CASCADE".to_string(),
        on_update: String::new(),
    }];
    create.checks = vec![CreateTableCheck {
        id: 1,
        name: "ck_t16_orders_amount".to_string(),
        expression: "amount >= 0".to_string(),
        not_enforced: false,
    }];

    let ddl = create.sql_preview().expect("PG 建表预览应成功");
    setup.text = ddl.clone();
    let execution = connector
        .execute(&setup)
        .unwrap_or_else(|error| panic!("生成的 DDL 应能在真实 PG 执行：{error}\n{ddl}"));
    // execute 把语句级失败折进 summaries：必须逐条确认成功，否则会拿到「没建表」的假通过。
    let failed = execution
        .summaries
        .iter()
        .filter(|summary| !summary.success)
        .collect::<Vec<_>>();
    assert!(
        failed.is_empty(),
        "生成的 DDL 每条语句都应成功：{failed:#?}\n{ddl}"
    );

    // 回读元数据：路径带 schema，确认对象确实落在隔离 schema 内。
    let path = ObjectPath {
        connection_id: config.id,
        database: Some(database.clone()),
        schema: Some("t16_smoke".to_string()),
        name: "orders".to_string(),
        kind: ObjectKind::Table,
    };
    let indexes = connector.list_indexes(&path).expect("读取索引应成功");
    let unique = indexes
        .iter()
        .find(|index| index.name == "uq_t16_orders_customer_amount")
        .unwrap_or_else(|| panic!("唯一索引应在隔离 schema 内：{indexes:#?}"));
    assert!(unique.is_unique, "uq_t16_orders_customer_amount 应为唯一索引");
    assert_eq!(
        unique.columns,
        vec!["customer_id".to_string(), "amount".to_string()],
        "索引列顺序应与设计一致：{unique:#?}"
    );
    assert!(
        indexes.iter().any(|index| index.is_primary),
        "identity 主键应落库：{indexes:#?}"
    );

    let foreign_keys = connector.list_foreign_keys(&path).expect("读取外键应成功");
    let foreign_key = foreign_keys
        .iter()
        .find(|foreign_key| foreign_key.name == "fk_t16_orders_customer")
        .unwrap_or_else(|| panic!("外键应在隔离 schema 内：{foreign_keys:#?}"));
    assert_eq!(foreign_key.ref_table, "customers");
    assert_eq!(foreign_key.column, "customer_id");
    assert_eq!(foreign_key.ref_column, "id");

    let ddl_readback = connector.table_ddl(&path).expect("读取表 DDL 应成功");
    assert!(ddl_readback.contains("customer_id"), "{ddl_readback}");
    assert!(ddl_readback.contains("amount"), "{ddl_readback}");
    assert!(
        ddl_readback.contains("ck_t16_orders_amount") || ddl_readback.contains("amount >= 0"),
        "check 约束应可回读：{ddl_readback}"
    );
    assert!(
        ddl_readback.contains("订单表"),
        "表注释应可回读：{ddl_readback}"
    );

    // 联合主键 + 触发器（引用隔离 schema 内已存在函数）：一并落库并回读。
    let mut composite = CreateTableState::new(config.id, Some(database.clone()), DatabaseKind::Postgres);
    composite.schema = "t16_smoke".to_string();
    composite.table_name = "order_items".to_string();
    let mut first = CreateTableColumn::new(1, provider);
    first.name = "order_id".to_string();
    first.data_type = "integer".to_string();
    first.nullable = false;
    first.primary_key = true;
    let mut second = CreateTableColumn::new(2, provider);
    second.name = "line_no".to_string();
    second.data_type = "integer".to_string();
    second.nullable = false;
    second.primary_key = true;
    let mut quantity = CreateTableColumn::new(3, provider);
    quantity.name = "quantity".to_string();
    quantity.data_type = "integer".to_string();
    quantity.nullable = false;
    quantity.default_value = "1".to_string();
    composite.columns = vec![first, second, quantity];
    composite.triggers = vec![CreateTableTrigger {
        id: 1,
        name: "trg_t16_order_items".to_string(),
        timing: "BEFORE".to_string(),
        event: "INSERT".to_string(),
        body: "t16_smoke.t16_audit".to_string(),
    }];

    let mut trigger_setup = setup.clone();
    trigger_setup.text = "CREATE FUNCTION t16_smoke.t16_audit() RETURNS trigger AS $$ BEGIN RETURN NEW; END; $$ LANGUAGE plpgsql;".to_string();
    let trigger_execution = connector.execute(&trigger_setup).expect("建触发器函数应成功");
    assert!(trigger_execution.summaries.iter().all(|summary| summary.success), "{trigger_execution:#?}");

    let composite_ddl = composite.sql_preview().expect("联合主键建表预览应成功");
    assert!(
        composite_ddl.contains("PRIMARY KEY (\"order_id\", \"line_no\")"),
        "联合主键应内联为组合主键：{composite_ddl}"
    );
    trigger_setup.text = composite_ddl.clone();
    let composite_execution = connector.execute(&trigger_setup).expect("联合主键建表应成功");
    let failed = composite_execution
        .summaries
        .iter()
        .filter(|summary| !summary.success)
        .collect::<Vec<_>>();
    assert!(failed.is_empty(), "联合主键/触发器 DDL 应全部成功：{failed:#?}\n{composite_ddl}");

    let composite_path = ObjectPath {
        name: "order_items".to_string(),
        ..path.clone()
    };
    let composite_indexes = connector.list_indexes(&composite_path).expect("读取联合主键索引应成功");
    let primary = composite_indexes
        .iter()
        .find(|index| index.is_primary)
        .unwrap_or_else(|| panic!("联合主键索引应落库：{composite_indexes:#?}"));
    assert_eq!(
        primary.columns,
        vec!["order_id".to_string(), "line_no".to_string()],
        "联合主键列顺序应与设计一致：{primary:#?}"
    );
    let triggers = connector.list_triggers(&composite_path).expect("读取触发器应成功");
    assert!(
        triggers.iter().any(|trigger| trigger.name == "trg_t16_order_items"),
        "触发器应落库：{triggers:#?}"
    );

    // 隔离 schema 不在默认 search_path：public 下不应出现同名表。
    let public_path = ObjectPath {
        schema: Some("public".to_string()),
        ..path.clone()
    };
    assert!(
        connector.table_ddl(&public_path).is_err(),
        "同名对象不应出现在 public"
    );

    let mut cleanup = setup;
    cleanup.text = "DROP SCHEMA IF EXISTS t16_smoke CASCADE;".to_string();
    connector.execute(&cleanup).expect("清理隔离 schema 应成功");
}

/// 解析 `FLUXDB_PG_SMOKE=host:port:user:password:db`。
fn postgres_create_table_smoke_params() -> Option<(String, u16, String, String, String)> {
    let value = std::env::var("FLUXDB_PG_SMOKE").ok()?;
    let mut parts = value.split(':');
    let host = parts.next()?.to_string();
    let port: u16 = parts.next()?.parse().ok()?;
    let user = parts.next()?.to_string();
    let password = parts.next()?.to_string();
    let db = parts.next()?.to_string();
    Some((host, port, user, password, db))
}

fn postgres_create_table_smoke_config(
    (host, port, user, password, db): &(String, u16, String, String, String),
) -> ConnectionConfig {
    ConnectionConfig {
        id: ConnectionId(9),
        name: "PG T16 Smoke".to_string(),
        kind: DatabaseKind::Postgres,
        endpoint: Endpoint::Tcp {
            host: host.clone(),
            port: *port,
            database: Some(db.clone()),
        },
        credential_ref: None,
        options: Default::default(),
        redis_profile: None,
        mysql_profile: None,
        postgres_profile: Some(fluxdb_core::PostgresConnectionProfile {
            basic: fluxdb_core::PostgresBasicOptions {
                host: host.clone(),
                port: *port,
                maintenance_database: db.clone(),
                username: user.clone(),
                password: fluxdb_core::SecretRef::inline(password),
            },
            ..Default::default()
        }),
    }
}
