/// T16 验收：生成的 PG 建表 DDL 在真实数据库隔离 schema 内重建后元数据对等。
///
/// 用 `FLUXDB_PG_SMOKE=host:port:user:password:db` 开启真实 PG 冒烟；未配置时跳过。
/// 断言覆盖：列/联合主键/唯一索引/FK/check/表列注释全部落库，且回读元数据与设计一致。
#[test]
fn postgres_create_table_ddl_rebuilds_equivalent_metadata() {
    let Some(params) = postgres_create_table_smoke_params() else {
        tracing::warn!(target: "fluxdb_app", "未设置 FLUXDB_PG_SMOKE，跳过真实 PG T16 冒烟");
        return;
    };
    let config = postgres_create_table_smoke_config(&params);
    let connector = PostgresConnector::with_config(config.clone());
    let database = params.4.clone();

    let mut setup = QueryRequest {
        connection_id: config.id,
        database: Some(database.clone()),
        session_id: None,
        schema: None,
        text: "\
            DROP SCHEMA IF EXISTS t16_smoke CASCADE; \
            CREATE SCHEMA t16_smoke; \
            CREATE TABLE t16_smoke.customers(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL); \
        "
        .to_string(),
        mode: fluxdb_core::QueryMode::All,
        options: QueryExecutionOptions::default(),
    };
    connector.execute(&setup).expect("建隔离 schema 应成功");

    // 领域结构 → DDL（provider 生成，UI 不拼 SQL）。
    let provider = create_table_provider(DatabaseKind::Postgres);
    let mut create = CreateTableState::new(config.id, Some(database.clone()), DatabaseKind::Postgres);
    create.schema = "t16_smoke".to_string();
    create.table_name = "orders".to_string();
    create.comment = "订单表".to_string();

    let mut id_column = CreateTableColumn::new(1, provider);
    id_column.name = "id".to_string();
    id_column.data_type = "integer".to_string();
    id_column.nullable = false;
    id_column.primary_key = true;
    id_column.auto_increment = true;
    id_column.comment = "主键".to_string();
    let mut customer_column = CreateTableColumn::new(2, provider);
    customer_column.name = "customer_id".to_string();
    customer_column.data_type = "integer".to_string();
    customer_column.nullable = false;
    let mut amount_column = CreateTableColumn::new(3, provider);
    amount_column.name = "amount".to_string();
    amount_column.data_type = "numeric".to_string();
    amount_column.length = "10".to_string();
    amount_column.scale = "2".to_string();
    amount_column.nullable = false;
    amount_column.default_value = "0".to_string();
    let mut note_column = CreateTableColumn::new(4, provider);
    note_column.name = "note".to_string();
    note_column.data_type = "text".to_string();
    note_column.nullable = true;
    create.columns = vec![id_column, customer_column, amount_column, note_column];

    create.indexes = vec![CreateTableIndex {
        id: 1,
        name: "uq_t16_orders_customer_amount".to_string(),
        columns: vec![
            CreateTableIndexColumn {
                name: "customer_id".to_string(),
                sub_part: String::new(),
                sort_order: String::new(),
            },
            CreateTableIndexColumn {
                name: "amount".to_string(),
                sub_part: String::new(),
                sort_order: String::new(),
            },
        ],
        index_type: "UNIQUE".to_string(),
        index_method: String::new(),
        comment: String::new(),
    }];
    create.foreign_keys = vec![CreateTableForeignKey {
        id: 1,
        name: "fk_t16_orders_customer".to_string(),
        columns: vec!["customer_id".to_string()],
        referenced_database: "t16_smoke".to_string(),
        referenced_table: "customers".to_string(),
        referenced_columns: vec!["id".to_string()],
        referenced_column_options: LoadState::Loaded(vec!["id".to_string()]),
        on_delete: "CASCADE".to_string(),
        on_update: String::new(),
    }];
    create.checks = vec![CreateTableCheck {
        id: 1,
        name: "ck_t16_orders_amount".to_string(),
        expression: "amount >= 0".to_string(),
        not_enforced: false,
    }];

    let ddl = create.sql_preview().expect("PG 建表预览应成功");
    setup.text = ddl.clone();
    let execution = connector
        .execute(&setup)
        .unwrap_or_else(|error| panic!("生成的 DDL 应能在真实 PG 执行：{error}\n{ddl}"));
    // execute 把语句级失败折进 summaries：必须逐条确认成功，否则会拿到「没建表」的假通过。
    let failed = execution
        .summaries
        .iter()
        .filter(|summary| !summary.success)
        .collect::<Vec<_>>();
    assert!(
        failed.is_empty(),
        "生成的 DDL 每条语句都应成功：{failed:#?}\n{ddl}"
    );

    // 回读元数据：路径带 schema，确认对象确实落在隔离 schema 内。
    let path = ObjectPath {
        connection_id: config.id,
        database: Some(database.clone()),
        schema: Some("t16_smoke".to_string()),
        name: "orders".to_string(),
        kind: ObjectKind::Table,
    };
    let indexes = connector.list_indexes(&path).expect("读取索引应成功");
    let unique = indexes
        .iter()
        .find(|index| index.name == "uq_t16_orders_customer_amount")
        .unwrap_or_else(|| panic!("唯一索引应在隔离 schema 内：{indexes:#?}"));
    assert!(unique.is_unique, "uq_t16_orders_customer_amount 应为唯一索引");
    assert_eq!(
        unique.columns,
        vec!["customer_id".to_string(), "amount".to_string()],
        "索引列顺序应与设计一致：{unique:#?}"
    );
    assert!(
        indexes.iter().any(|index| index.is_primary),
        "identity 主键应落库：{indexes:#?}"
    );

    let foreign_keys = connector.list_foreign_keys(&path).expect("读取外键应成功");
    let foreign_key = foreign_keys
        .iter()
        .find(|foreign_key| foreign_key.name == "fk_t16_orders_customer")
        .unwrap_or_else(|| panic!("外键应在隔离 schema 内：{foreign_keys:#?}"));
    assert_eq!(foreign_key.ref_table, "customers");
    assert_eq!(foreign_key.column, "customer_id");
    assert_eq!(foreign_key.ref_column, "id");

    let ddl_readback = connector.table_ddl(&path).expect("读取表 DDL 应成功");
    assert!(ddl_readback.contains("customer_id"), "{ddl_readback}");
    assert!(ddl_readback.contains("amount"), "{ddl_readback}");
    assert!(
        ddl_readback.contains("ck_t16_orders_amount") || ddl_readback.contains("amount >= 0"),
        "check 约束应可回读：{ddl_readback}"
    );
    assert!(
        ddl_readback.contains("订单表"),
        "表注释应可回读：{ddl_readback}"
    );

    // 联合主键 + 触发器（引用隔离 schema 内已存在函数）：一并落库并回读。
    let mut composite = CreateTableState::new(config.id, Some(database.clone()), DatabaseKind::Postgres);
    composite.schema = "t16_smoke".to_string();
    composite.table_name = "order_items".to_string();
    let mut first = CreateTableColumn::new(1, provider);
    first.name = "order_id".to_string();
    first.data_type = "integer".to_string();
    first.nullable = false;
    first.primary_key = true;
    let mut second = CreateTableColumn::new(2, provider);
    second.name = "line_no".to_string();
    second.data_type = "integer".to_string();
    second.nullable = false;
    second.primary_key = true;
    let mut quantity = CreateTableColumn::new(3, provider);
    quantity.name = "quantity".to_string();
    quantity.data_type = "integer".to_string();
    quantity.nullable = false;
    quantity.default_value = "1".to_string();
    composite.columns = vec![first, second, quantity];
    composite.triggers = vec![CreateTableTrigger {
        id: 1,
        name: "trg_t16_order_items".to_string(),
        timing: "BEFORE".to_string(),
        event: "INSERT".to_string(),
        body: "t16_smoke.t16_audit".to_string(),
    }];

    let mut trigger_setup = setup.clone();
    trigger_setup.text = "CREATE FUNCTION t16_smoke.t16_audit() RETURNS trigger AS $$ BEGIN RETURN NEW; END; $$ LANGUAGE plpgsql;".to_string();
    let trigger_execution = connector.execute(&trigger_setup).expect("建触发器函数应成功");
    assert!(trigger_execution.summaries.iter().all(|summary| summary.success), "{trigger_execution:#?}");

    let composite_ddl = composite.sql_preview().expect("联合主键建表预览应成功");
    assert!(
        composite_ddl.contains("PRIMARY KEY (\"order_id\", \"line_no\")"),
        "联合主键应内联为组合主键：{composite_ddl}"
    );
    trigger_setup.text = composite_ddl.clone();
    let composite_execution = connector.execute(&trigger_setup).expect("联合主键建表应成功");
    let failed = composite_execution
        .summaries
        .iter()
        .filter(|summary| !summary.success)
        .collect::<Vec<_>>();
    assert!(failed.is_empty(), "联合主键/触发器 DDL 应全部成功：{failed:#?}\n{composite_ddl}");

    let composite_path = ObjectPath {
        name: "order_items".to_string(),
        ..path.clone()
    };
    let composite_indexes = connector.list_indexes(&composite_path).expect("读取联合主键索引应成功");
    let primary = composite_indexes
        .iter()
        .find(|index| index.is_primary)
        .unwrap_or_else(|| panic!("联合主键索引应落库：{composite_indexes:#?}"));
    assert_eq!(
        primary.columns,
        vec!["order_id".to_string(), "line_no".to_string()],
        "联合主键列顺序应与设计一致：{primary:#?}"
    );
    let triggers = connector.list_triggers(&composite_path).expect("读取触发器应成功");
    assert!(
        triggers.iter().any(|trigger| trigger.name == "trg_t16_order_items"),
        "触发器应落库：{triggers:#?}"
    );

    // 隔离 schema 不在默认 search_path：public 下不应出现同名表。
    let public_path = ObjectPath {
        schema: Some("public".to_string()),
        ..path.clone()
    };
    assert!(
        connector.table_ddl(&public_path).is_err(),
        "同名对象不应出现在 public"
    );

    let mut cleanup = setup;
    cleanup.text = "DROP SCHEMA IF EXISTS t16_smoke CASCADE;".to_string();
    connector.execute(&cleanup).expect("清理隔离 schema 应成功");
}

/// 直接把设计状态挂成一个 tab（测试内构造状态，等价于 UI 里已打开的设计器）。
fn push_create_table_tab(controller: &mut AppController, create: CreateTableState) -> TabId {
    let tab_id = TabId(900 + controller.state.tabs.len() as u64);
    controller.state.tabs.push(TabState {
        id: tab_id,
        title: "设计表".to_string(),
        kind: TabKind::CreateTable(create),
        dirty: true,
    });
    controller.state.active_tab = Some(tab_id);
    tab_id
}

/// 解析 `FLUXDB_PG_SMOKE=host:port:user:password:db`。
fn postgres_create_table_smoke_params() -> Option<(String, u16, String, String, String)> {
    let value = std::env::var("FLUXDB_PG_SMOKE").ok()?;
    let mut parts = value.split(':');
    let host = parts.next()?.to_string();
    let port: u16 = parts.next()?.parse().ok()?;
    let user = parts.next()?.to_string();
    let password = parts.next()?.to_string();
    let db = parts.next()?.to_string();
    Some((host, port, user, password, db))
}

fn postgres_create_table_smoke_config(
    (host, port, user, password, db): &(String, u16, String, String, String),
) -> ConnectionConfig {
    ConnectionConfig {
        id: ConnectionId(9),
        name: "PG T16 Smoke".to_string(),
        kind: DatabaseKind::Postgres,
        endpoint: Endpoint::Tcp {
            host: host.clone(),
            port: *port,
            database: Some(db.clone()),
        },
        credential_ref: None,
        options: Default::default(),
        redis_profile: None,
        mysql_profile: None,
        postgres_profile: Some(fluxdb_core::PostgresConnectionProfile {
            basic: fluxdb_core::PostgresBasicOptions {
                host: host.clone(),
                port: *port,
                maintenance_database: db.clone(),
                username: user.clone(),
                password: fluxdb_core::SecretRef::inline(password),
            },
            ..Default::default()
        }),
    }
}

/// T17 验收：PG 设计差异在真实库执行（同一事务），外部 DDL 后拒绝应用过期快照。
#[test]
fn postgres_design_diff_applies_atomically_and_blocks_stale_snapshot() {
    let Some(params) = postgres_create_table_smoke_params() else {
        tracing::warn!(target: "fluxdb_app", "未设置 FLUXDB_PG_SMOKE，跳过真实 PG T17 冒烟");
        return;
    };
    let config = postgres_create_table_smoke_config(&params);
    let mut controller = AppController::with_mock_data();
    let AppEvent::ConnectionCreated(registered) = controller.dispatch(AppCommand::CreateConnection(
        ConnectionDraft {
            name: "PG T17 Smoke".to_string(),
            kind: DatabaseKind::Postgres,
            endpoint: config.endpoint.clone(),
            credential_ref: None,
            options: Default::default(),
            redis_profile: None,
            mysql_profile: None,
            postgres_profile: config.postgres_profile.clone(),
        },
    )) else {
        panic!("注册 PG 连接应成功");
    };
    let connector = PostgresConnector::with_config(registered.clone());
    let database = params.4.clone();

    let mut request = QueryRequest {
        connection_id: registered.id,
        database: Some(database.clone()),
        session_id: None,
        schema: None,
        text: "\
            DROP SCHEMA IF EXISTS t17_smoke CASCADE; \
            CREATE SCHEMA t17_smoke; \
            CREATE TABLE t17_smoke.orders(id integer PRIMARY KEY, note text); \
            CREATE INDEX idx_t17_orders_note ON t17_smoke.orders(note); \
        "
        .to_string(),
        mode: fluxdb_core::QueryMode::All,
        options: QueryExecutionOptions::default(),
    };
    connector.execute(&request).expect("准备隔离 schema 应成功");

    // 打开设计器：元数据 + DDL 作为原始快照。
    let object = ObjectPath {
        connection_id: registered.id,
        database: Some(database.clone()),
        schema: Some("t17_smoke".to_string()),
        name: "orders".to_string(),
        kind: ObjectKind::Table,
    };
    let columns = connector
        .list_completion_columns(Some(&database), Some("t17_smoke"), "orders")
        .expect("读取列元数据应成功");
    let ddl = connector.table_ddl(&object).expect("读取 DDL 应成功");
    let indexes = connector.list_indexes(&object).expect("读取索引应成功");
    let mut create = CreateTableState::design(
        object.clone(),
        DatabaseKind::Postgres,
        columns,
        indexes,
        Vec::new(),
        Vec::new(),
        Some(ddl.clone()),
    );
    assert!(
        create.sql_preview().is_err(),
        "未修改的设计不应产生 SQL：{:?}",
        create.sql_preview()
    );

    // 追加一列 + 改表注释 + 新增唯一索引 → 预览为差异动作。
    let mut quantity = CreateTableColumn::new(3, create_table_provider(DatabaseKind::Postgres));
    quantity.name = "quantity".to_string();
    quantity.data_type = "integer".to_string();
    quantity.nullable = false;
    quantity.default_value = "1".to_string();
    create.columns.push(quantity);
    create.comment = "订单表".to_string();
    create.indexes.push(CreateTableIndex {
        id: 99,
        name: "uq_t17_orders_note".to_string(),
        columns: vec![CreateTableIndexColumn {
            name: "note".to_string(),
            sub_part: String::new(),
            sort_order: String::new(),
        }],
        index_type: "UNIQUE".to_string(),
        index_method: String::new(),
        comment: String::new(),
    });

    let preview = create.sql_preview().expect("设计预览应成功");
    assert!(
        preview.contains("ADD COLUMN \"quantity\" integer NOT NULL DEFAULT 1;"),
        "{preview}"
    );
    assert!(preview.contains("CREATE UNIQUE INDEX"), "{preview}");

    // 先把设计挂成 tab（等价于 UI 里已打开的设计器），再模拟外部 DDL 改动结构。
    let design_tab = push_create_table_tab(&mut controller, create.clone());

    request.text = "ALTER TABLE t17_smoke.orders ADD COLUMN external_col text;".to_string();
    let external = connector.execute(&request).expect("外部 DDL 应成功");
    assert!(external.summaries.iter().all(|summary| summary.success));

    let AppEvent::Failed(error) = controller.dispatch(AppCommand::ApplyCreateTable(design_tab))
    else {
        panic!("过期设计应被拒绝");
    };
    assert!(
        error.message.contains("结构已在外部变化"),
        "错误应说明结构已变化：{error:?}"
    );

    // 刷新后（按最新 DDL 重建基线）可以正常保存，差异在事务内执行。
    // 与真实打开路径一致：基线 DDL 需经 format_sql_text_for_dialect 规整，否则与校验侧不一致。
    let refreshed_ddl = format_sql_text_for_dialect(
        &connector.table_ddl(&object).expect("重新读取 DDL 应成功"),
        DatabaseKind::Postgres,
    );
    let mut refreshed = create.clone();
    if let CreateTableMode::Design {
        original_ddl,
        original,
        ..
    } = &mut refreshed.mode
    {
        *original_ddl = Some(refreshed_ddl);
        // 外部新增的列并入基线，避免被当成「用户要删除的列」。
        let mut external_column =
            CreateTableColumn::new(77, create_table_provider(DatabaseKind::Postgres));
        external_column.name = "external_col".to_string();
        external_column.data_type = "text".to_string();
        external_column.nullable = true;
        original.columns.push(external_column.clone());
        refreshed.columns.push(external_column);
    }
    if let Some(tab) = controller.state.tabs.iter_mut().find(|tab| tab.id == design_tab)
        && let TabKind::CreateTable(state) = &mut tab.kind
    {
        *state = refreshed;
    }
    assert!(
        matches!(
            controller.dispatch(AppCommand::ApplyCreateTable(design_tab)),
            AppEvent::CreateTableApplied(_)
        ),
        "刷新后的设计应可保存"
    );

    // 落库校验：新列与注释生效，索引建立。
    let page = connector
        .load_data(&object, 0, 10, &[], &[])
        .expect("读取数据应成功");
    let names = page
        .columns
        .iter()
        .map(|column| column.name.as_str())
        .collect::<Vec<_>>();
    assert!(names.contains(&"quantity"), "新列应落库：{names:?}");
    assert!(names.contains(&"external_col"), "外部列不应被删除：{names:?}");
    let indexes = connector.list_indexes(&object).expect("读取索引应成功");
    assert!(
        indexes
            .iter()
            .any(|index| index.name == "uq_t17_orders_note" && index.is_unique),
        "新唯一索引应落库：{indexes:#?}"
    );
    assert!(
        connector
            .table_ddl(&object)
            .expect("读取 DDL 应成功")
            .contains("订单表"),
        "表注释应落库"
    );

    // 失败整体回滚：第二条语句非法时，前面的 ADD COLUMN 也不应留下。
    request.text = "DROP SCHEMA IF EXISTS t17_rollback CASCADE; CREATE SCHEMA t17_rollback; \
                    CREATE TABLE t17_rollback.t(id integer PRIMARY KEY);"
        .to_string();
    connector.execute(&request).expect("准备回滚验证表应成功");
    let rollback_object = ObjectPath {
        schema: Some("t17_rollback".to_string()),
        name: "t".to_string(),
        ..object.clone()
    };
    let rollback_columns = connector
        .list_completion_columns(Some(&database), Some("t17_rollback"), "t")
        .expect("读取列元数据应成功");
    let mut failing = CreateTableState::design(
        rollback_object.clone(),
        DatabaseKind::Postgres,
        rollback_columns,
        Vec::new(),
        Vec::new(),
        Vec::new(),
        Some(
            connector
                .table_ddl(&rollback_object)
                .expect("读取 DDL 应成功"),
        ),
    );
    let mut ok_column = CreateTableColumn::new(2, create_table_provider(DatabaseKind::Postgres));
    ok_column.name = "added_ok".to_string();
    ok_column.data_type = "integer".to_string();
    ok_column.nullable = true;
    let mut broken_column = CreateTableColumn::new(3, create_table_provider(DatabaseKind::Postgres));
    broken_column.name = "added_bad".to_string();
    broken_column.data_type = "integer".to_string();
    broken_column.nullable = true;
    broken_column.default_value = "not_a_number".to_string();
    failing.columns = vec![
        failing.columns[0].clone(),
        ok_column,
        broken_column,
    ];
    let tab_id = push_create_table_tab(&mut controller, failing);
    assert!(
        matches!(
            controller.dispatch(AppCommand::ApplyCreateTable(tab_id)),
            AppEvent::Failed(_)
        ),
        "非法默认值应导致失败"
    );
    let after = connector
        .list_completion_columns(Some(&database), Some("t17_rollback"), "t")
        .expect("读取列元数据应成功");
    let after_names = after
        .iter()
        .map(|column| column.name.as_str())
        .collect::<Vec<_>>();
    assert_eq!(
        after_names,
        vec!["id"],
        "失败应整体回滚，不留半套结构：{after_names:?}"
    );

    request.text = "DROP SCHEMA IF EXISTS t17_smoke CASCADE; DROP SCHEMA IF EXISTS t17_rollback CASCADE;"
        .to_string();
    connector.execute(&request).expect("清理隔离 schema 应成功");
}

/// T18 验收：PG 复制表后源/目标自增独立，数据可复制，且不复制源序列。
#[test]
fn postgres_copy_table_gets_independent_sequence() {
    let Some(params) = postgres_create_table_smoke_params() else {
        tracing::warn!(target: "fluxdb_app", "未设置 FLUXDB_PG_SMOKE，跳过真实 PG T18 冒烟");
        return;
    };
    let config = postgres_create_table_smoke_config(&params);
    let connector = PostgresConnector::with_config(config.clone());
    let database = params.4.clone();

    let mut request = QueryRequest {
        connection_id: config.id,
        database: Some(database.clone()),
        session_id: None,
        schema: None,
        text: "\
            DROP SCHEMA IF EXISTS t18_smoke CASCADE; \
            CREATE SCHEMA t18_smoke; \
            CREATE TABLE t18_smoke.orders( \
                id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY, \
                note text, \
                upper_note text GENERATED ALWAYS AS (upper(note)) STORED \
            ); \
            INSERT INTO t18_smoke.orders(note) VALUES ('a'), ('b'); \
        "
        .to_string(),
        mode: fluxdb_core::QueryMode::All,
        options: QueryExecutionOptions::default(),
    };
    let setup = connector.execute(&request).expect("准备隔离 schema 应成功");
    assert!(setup.summaries.iter().all(|summary| summary.success));

    // 复制（结构 + 数据）：provider 生成 SQL，逐条事务执行。
    let copy = copy_table_sql_preview(
        DatabaseKind::Postgres,
        Some("t18_smoke"),
        "orders",
        "orders_copy",
        true,
    )
    .expect("复制预览应成功");
    let mut copy_request = request.clone();
    copy_request.text = format!("BEGIN;\n{copy}\nCOMMIT;");
    let copied = connector.execute(&copy_request).expect("复制应执行成功");
    let failed = copied
        .summaries
        .iter()
        .filter(|summary| !summary.success)
        .collect::<Vec<_>>();
    assert!(failed.is_empty(), "复制语句应全部成功：{failed:#?}\n{copy}");

    // 数据被复制。
    let page = connector
        .load_data(
            &ObjectPath {
                connection_id: config.id,
                database: Some(database.clone()),
                schema: Some("t18_smoke".to_string()),
                name: "orders_copy".to_string(),
                kind: ObjectKind::Table,
            },
            0,
            10,
            &[],
            &[],
        )
        .expect("读取副本应成功");
    assert_eq!(page.rows.len(), 2, "副本应含 2 行数据");

    // 源/目标序列独立：向副本插入 2 行不应推进源序列，再向源插入也不与副本冲突。
    request.text = "\
        INSERT INTO t18_smoke.orders_copy(note) VALUES ('c'), ('d'); \
        INSERT INTO t18_smoke.orders(note) VALUES ('e'); \
    "
    .to_string();
    let inserted = connector.execute(&request).expect("插入应成功");
    assert!(
        inserted.summaries.iter().all(|summary| summary.success),
        "源/目标自增应互不干扰：{inserted:#?}"
    );

    // 各表内部主键唯一（副本后续插入不与已复制数据冲突）。
    request.text = "SELECT (SELECT count(*) FROM t18_smoke.orders) AS src_rows, \
                            (SELECT count(DISTINCT id) FROM t18_smoke.orders) AS src_ids, \
                            (SELECT count(*) FROM t18_smoke.orders_copy) AS dst_rows, \
                            (SELECT count(DISTINCT id) FROM t18_smoke.orders_copy) AS dst_ids;"
        .to_string();
    let counted = connector.execute(&request).expect("统计应成功");
    let counts = counted
        .results
        .last()
        .and_then(|page| page.rows.first())
        .map(|row| row.values.clone())
        .unwrap_or_default();
    assert_eq!(
        counts,
        vec![
            CellValue::I64(3),
            CellValue::I64(3),
            CellValue::I64(4),
            CellValue::I64(4)
        ],
        "源 3 行、副本 4 行且各自主键唯一：{counts:?}"
    );

    // 序列独立：副本的默认序列不是源序列，且源序列位置未被副本插入推进（仍为 3）。
    // 生成列由服务端重算（复制时不写入）：副本的 upper_note 有值且等于 note 大写。
    request.text = "SELECT count(*) FROM t18_smoke.orders_copy \
                            WHERE upper_note IS DISTINCT FROM upper(note);"
        .to_string();
    let generated = connector.execute(&request).expect("读取生成列应成功");
    let mismatched = generated
        .results
        .last()
        .and_then(|page| page.rows.first())
        .map(|row| row.values.clone())
        .unwrap_or_default();
    assert_eq!(
        mismatched,
        vec![CellValue::I64(0)],
        "生成列应由服务端重算且不参与写入：{mismatched:?}"
    );

    request.text = "SELECT pg_get_serial_sequence('t18_smoke.orders_copy', 'id') <> \
                            pg_get_serial_sequence('t18_smoke.orders', 'id') AS independent, \
                            (SELECT last_value FROM pg_sequences \
                              WHERE schemaname = 't18_smoke' AND sequencename = 'orders_id_seq') AS source_seq;"
        .to_string();
    let sequence = connector.execute(&request).expect("读取序列应成功");
    let values = sequence
        .results
        .last()
        .and_then(|page| page.rows.first())
        .map(|row| row.values.clone())
        .unwrap_or_default();
    assert_eq!(
        values,
        vec![CellValue::Bool(true), CellValue::I64(3)],
        "副本必须使用独立序列，源序列不应被副本插入推进：{values:?}"
    );

    request.text =
        "DROP SCHEMA IF EXISTS t18_smoke CASCADE;".to_string();
    connector.execute(&request).expect("清理隔离 schema 应成功");
}

/// 复现：设计器内加索引后直接保存（无外部 DDL 改动），不应误判为「外部变化」。
#[test]
fn postgres_design_save_without_external_change_succeeds() {
    let Some(params) = postgres_create_table_smoke_params() else {
        tracing::warn!(target: "fluxdb_app", "未设置 FLUXDB_PG_SMOKE，跳过复现冒烟");
        return;
    };
    let config = postgres_create_table_smoke_config(&params);
    let mut controller = AppController::with_mock_data();
    let AppEvent::ConnectionCreated(registered) = controller.dispatch(AppCommand::CreateConnection(
        ConnectionDraft {
            name: "PG REPRO Smoke".to_string(),
            kind: DatabaseKind::Postgres,
            endpoint: config.endpoint.clone(),
            credential_ref: None,
            options: Default::default(),
            redis_profile: None,
            mysql_profile: None,
            postgres_profile: config.postgres_profile.clone(),
        },
    )) else {
        panic!("注册 PG 连接应成功");
    };
    let connector = PostgresConnector::with_config(registered.clone());
    let database = params.4.clone();

    let mut request = QueryRequest {
        connection_id: registered.id,
        database: Some(database.clone()),
        session_id: None,
        schema: None,
        text: "\
            DROP SCHEMA IF EXISTS repro_smoke CASCADE; \
            CREATE SCHEMA repro_smoke; \
            CREATE TABLE repro_smoke.customers(id integer PRIMARY KEY, name text); \
            CREATE TABLE repro_smoke.orders(\
                id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, \
                phone text COLLATE \"C\", \
                full_name text GENERATED ALWAYS AS (phone) STORED, \
                email text, note text, customer_id integer, \
                CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) \
                    REFERENCES repro_smoke.customers(id) ON DELETE SET NULL, \
                CONSTRAINT uq_orders_email UNIQUE (email)); \
            COMMENT ON TABLE repro_smoke.orders IS '订单'; \
            COMMENT ON COLUMN repro_smoke.orders.note IS '备注'; \
            CREATE INDEX idx_orders_note ON repro_smoke.orders(note); \
        "
        .to_string(),
        mode: fluxdb_core::QueryMode::All,
        options: QueryExecutionOptions::default(),
    };
    connector.execute(&request).expect("准备隔离 schema 应成功");

    let object = ObjectPath {
        connection_id: registered.id,
        database: Some(database.clone()),
        schema: Some("repro_smoke".to_string()),
        name: "orders".to_string(),
        kind: ObjectKind::Table,
    };
    let columns = connector
        .list_completion_columns(Some(&database), Some("repro_smoke"), "orders")
        .expect("读取列元数据应成功");
    // 打开设计器的真实路径经 controller 的 load_table_info_for_connection 返回规整后的 DDL
    //（format_sql_text_for_dialect）。测试需与之一致，否则基线形态对不上校验侧。
    let ddl = format_sql_text_for_dialect(
        &connector.table_ddl(&object).expect("读取 DDL 应成功"),
        DatabaseKind::Postgres,
    );
    let indexes = connector.list_indexes(&object).expect("读取索引应成功");
    let mut create = CreateTableState::design(
        object.clone(),
        DatabaseKind::Postgres,
        columns,
        indexes,
        Vec::new(),
        Vec::new(),
        Some(ddl.clone()),
    );

    // 设计器里加唯一索引（与用户操作一致），不改外部结构。
    create.indexes.push(CreateTableIndex {
        id: 99,
        name: "idx_phone".to_string(),
        columns: vec![CreateTableIndexColumn {
            name: "phone".to_string(),
            sub_part: String::new(),
            sort_order: String::new(),
        }],
        index_type: "UNIQUE".to_string(),
        index_method: String::new(),
        comment: String::new(),
    });

    let design_tab = push_create_table_tab(&mut controller, create.clone());
    match controller.dispatch(AppCommand::ApplyCreateTable(design_tab)) {
        AppEvent::CreateTableApplied(_) => {}
        other => panic!("无外部变化时保存应成功：{other:?}"),
    }
    // 走完真实 UI 流程：保存成功后通知控制器刷新设计基线。
    match controller.dispatch(AppCommand::FinishCreateTableApply {
        tab_id: design_tab,
        result: Ok(()),
    }) {
        AppEvent::CreateTableApplied(_) => {}
        other => panic!("保存收尾应成功：{other:?}"),
    }

    // 校验：保存后刷新基线，新 DDL 基线应已包含刚落库的 idx_phone 索引。
    let refreshed_ddl = controller
        .state
        .tabs
        .iter()
        .find(|tab| tab.id == design_tab)
        .and_then(|tab| match &tab.kind {
            TabKind::CreateTable(create) => match &create.mode {
                CreateTableMode::Design { original_ddl, .. } => original_ddl.clone(),
                _ => None,
            },
            _ => None,
        })
        .expect("设计基线 DDL 应存在");
    assert!(
        refreshed_ddl.contains("idx_phone"),
        "保存后基线 DDL 应包含已落库索引：\n{refreshed_ddl}"
    );

    // 同一设计器再加一个索引（未重开），不应被当成「外部变化」拒绝。
    if let Some(tab) = controller.state.tabs.iter_mut().find(|tab| tab.id == design_tab)
        && let TabKind::CreateTable(state) = &mut tab.kind
    {
        state.indexes.push(CreateTableIndex {
            id: 100,
            name: "idx_note".to_string(),
            columns: vec![CreateTableIndexColumn {
                name: "note".to_string(),
                sub_part: String::new(),
                sort_order: String::new(),
            }],
            index_type: String::new(),
            index_method: String::new(),
            comment: String::new(),
        });
    }
    match controller.dispatch(AppCommand::ApplyCreateTable(design_tab)) {
        AppEvent::CreateTableApplied(_) => {}
        other => panic!("同设计器连续保存第二处改动应成功：{other:?}"),
    }

    request.text = "DROP SCHEMA IF EXISTS repro_smoke CASCADE;".to_string();
    connector.execute(&request).expect("清理隔离 schema 应成功");
}
