#[test]
fn postgres_create_table_preview_covers_columns_keys_indexes_comments() {
    let mut create = CreateTableState::new(
        ConnectionId(9),
        Some("appdb".to_string()),
        DatabaseKind::Postgres,
    );
    create.schema = "sales".to_string();
    create.table_name = "orders".to_string();
    create.comment = "订单表".to_string();

    // identity 主键列（复用 auto_increment 能力位，PG 渲染为 GENERATED BY DEFAULT AS IDENTITY）。
    let provider = create_table_provider(DatabaseKind::Postgres);
    let mut id_column = CreateTableColumn::new(1, provider);
    id_column.name = "id".to_string();
    id_column.data_type = "integer".to_string();
    id_column.nullable = false;
    id_column.primary_key = true;
    id_column.auto_increment = true;
    let mut amount_column = CreateTableColumn::new(2, provider);
    amount_column.name = "amount".to_string();
    amount_column.data_type = "numeric".to_string();
    amount_column.length = "10".to_string();
    amount_column.scale = "2".to_string();
    amount_column.nullable = false;
    amount_column.default_value = "0".to_string();
    amount_column.comment = "金额".to_string();
    let mut customer_column = CreateTableColumn::new(3, provider);
    customer_column.name = "customer_id".to_string();
    customer_column.data_type = "integer".to_string();
    customer_column.nullable = false;
    create.columns = vec![id_column, amount_column, customer_column];
    create.indexes = vec![CreateTableIndex {
        id: 1,
        name: "idx_orders_amount".to_string(),
        columns: vec![CreateTableIndexColumn {
            name: "amount".to_string(),
            sub_part: String::new(),
            sort_order: "DESC".to_string(),
        }],
        index_type: "NORMAL".to_string(),
        index_method: "BTREE".to_string(),
        comment: String::new(),
    }];
    create.indexes.push(CreateTableIndex {
        id: 2,
        name: "uq_orders_customer".to_string(),
        columns: vec![CreateTableIndexColumn {
            name: "customer_id".to_string(),
            sub_part: String::new(),
            sort_order: String::new(),
        }],
        index_type: "UNIQUE".to_string(),
        index_method: String::new(),
        comment: String::new(),
    });
    create.foreign_keys = vec![CreateTableForeignKey {
        id: 1,
        name: "fk_orders_customer".to_string(),
        columns: vec!["customer_id".to_string()],
        referenced_database: "public".to_string(),
        referenced_table: "customers".to_string(),
        referenced_columns: vec!["id".to_string()],
        referenced_column_options: LoadState::Loaded(vec!["id".to_string()]),
        on_delete: "CASCADE".to_string(),
        on_update: String::new(),
    }];
    create.checks = vec![CreateTableCheck {
        id: 1,
        name: "ck_orders_amount".to_string(),
        expression: "amount >= 0".to_string(),
        not_enforced: false,
    }];

    let sql = create.sql_preview().expect("PG 建表预览应成功");

    // schema 限定 + 双引号标识符（不是 MySQL 反引号）。
    assert!(
        sql.starts_with("CREATE TABLE \"sales\".\"orders\" ("),
        "应带 schema 限定：{sql}"
    );
    // identity 而非 AUTO_INCREMENT。
    assert!(
        sql.contains("\"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL"),
        "identity 列应渲染为 GENERATED BY DEFAULT AS IDENTITY：{sql}"
    );
    assert!(!sql.contains("AUTO_INCREMENT"), "不得出现 MySQL 属性：{sql}");
    // numeric 精度保留。
    assert!(sql.contains("\"amount\" numeric(10,2) NOT NULL DEFAULT 0"), "{sql}");
    // 主键 / check 约束行。
    assert!(sql.contains("PRIMARY KEY (\"id\")"), "{sql}");
    assert!(
        sql.contains("CONSTRAINT \"ck_orders_amount\" CHECK (amount >= 0)"),
        "{sql}"
    );
    // FK：referenced_database 承载 schema，始终带限定（不依赖 search_path）。
    assert!(
        sql.contains(
            "CONSTRAINT \"fk_orders_customer\" FOREIGN KEY (\"customer_id\") REFERENCES \"public\".\"customers\" (\"id\") ON DELETE CASCADE"
        ),
        "{sql}"
    );
    // 注释是独立 COMMENT ON 语句。
    assert!(sql.contains("COMMENT ON TABLE \"sales\".\"orders\" IS '订单表';"), "{sql}");
    assert!(
        sql.contains("COMMENT ON COLUMN \"sales\".\"orders\".\"amount\" IS '金额';"),
        "{sql}"
    );
    // 索引：PG 的 CREATE [UNIQUE] INDEX（BTREE 是默认，不写 USING）。
    assert!(
        sql.contains(
            "CREATE INDEX \"idx_orders_amount\" ON \"sales\".\"orders\" (\"amount\" DESC);"
        ),
        "{sql}"
    );
    assert!(
        sql.contains("CREATE UNIQUE INDEX \"uq_orders_customer\" ON \"sales\".\"orders\" (\"customer_id\");"),
        "{sql}"
    );
}

#[test]
fn postgres_create_table_rejects_mysql_only_and_inline_trigger() {
    // identity 挂在非整数列：应拒绝而不是生成 PG 无法执行的 DDL。
    let mut create = CreateTableState::new(ConnectionId(9), None, DatabaseKind::Postgres);
    create.table_name = "t".to_string();
    let provider = create_table_provider(DatabaseKind::Postgres);
    let mut id_column = CreateTableColumn::new(1, provider);
    id_column.name = "id".to_string();
    id_column.data_type = "text".to_string();
    id_column.nullable = false;
    id_column.auto_increment = true;
    create.columns = vec![id_column];
    assert_eq!(
        create.validation_error(),
        Some("PostgreSQL identity 只能用于整数类型列")
    );

    // MySQL 行内 BEGIN…END 触发器体不是 PG 触发器：必须明确拒绝。
    create.columns[0].auto_increment = false;
    create.columns[0].primary_key = true;
    create.triggers = vec![CreateTableTrigger {
        id: 1,
        name: "tg".to_string(),
        timing: "BEFORE".to_string(),
        event: "INSERT".to_string(),
        body: "BEGIN RETURN NEW; END".to_string(),
    }];
    assert_eq!(
        create.validation_error(),
        Some("PostgreSQL 触发器需要引用已存在的函数，不支持行内 BEGIN…END 触发器体")
    );

    // 引用已存在函数则可生成 CREATE TRIGGER ... EXECUTE FUNCTION。
    create.triggers[0].body = "audit_row".to_string();
    let sql = create.sql_preview().expect("引用函数的触发器应可生成");
    assert!(
        sql.contains(
            "CREATE TRIGGER \"tg\" BEFORE INSERT ON \"t\" FOR EACH ROW EXECUTE FUNCTION \"audit_row\"();"
        ),
        "{sql}"
    );
}

#[test]
fn postgres_create_table_type_capabilities_hide_mysql_options() {
    let provider = create_table_provider(DatabaseKind::Postgres);
    assert_eq!(provider.default_column_type(), "text");
    assert_eq!(provider.default_id_type(), "integer");
    assert!(provider.type_options().contains(&"jsonb"));

    let integer = provider.type_capabilities("integer");
    assert!(integer.auto_increment, "整数列应可设 identity");
    assert!(!integer.unsigned && !integer.zerofill && !integer.auto_update_time);

    let varchar = provider.type_capabilities("varchar");
    assert!(varchar.length);
    assert!(!varchar.key_length && !varchar.binary_attribute && !varchar.text_options);

    let numeric = provider.type_capabilities("numeric");
    assert!(numeric.scale && !numeric.length);

    // 未列在类型清单里的 MySQL 类型不应带 MySQL 专属能力。
    let text_type = provider.type_capabilities("mediumtext");
    assert!(
        !text_type.length && !text_type.text_options && !text_type.auto_increment,
        "PG 不展示 MySQL 文本类型能力"
    );
}
